# Generated by Django 4.1.10 on 2023-08-11 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zomatobackend', '1_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]